redis:
    build: ./redis
    ports:
      - "6378:6379"
    restart: always
logstashagentkds:
    build: ./logstash
    volumes:
        - ~/sincedb/sincedb_opt_kds_shipper:/opt/sincedb
        - /home/ftp/logs:/home/ftp/logs
        - ~/opt-kds-shipper/htdocs/Dockerfiles/logstash/kds/agent.conf:/opt/logstash/conf/agent.conf
    command: logstash agent  -f /opt/logstash/conf/agent.conf 
    restart: always
